### ISSUE TITLE
HTMLProofer In GitHub Actions:

### ISSUE THREAD

**Issue by soprun** [soprun/soprun.github.io#15]
https://github.com/gjtorikian/html-proofer#caching-with-continuous-integration

```
      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
```
